# Generated by Django 4.1.7 on 2023-02-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0002_auto_20230223_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinoimage',
            name='image',
            field=models.FileField(upload_to='dinosaur_images/'),
        ),
    ]
